[package]
name = "missioncenter"
version = "0.1.0"
edition = "2021"
build = "build/build.rs"

[dependencies]
adw = { package = "libadwaita", version = "0.4", features = ["v1_3"] }
drm = { version = "0.9" }
egl = { version = "0.2" }
errno-sys = { version = "0.1" }
gbm = { version = "0.12" }
gettext-rs = { version = "0.7", features = ["gettext-system"] }
gl = { version = "0.14" }
gtk = { package = "gtk4", version = "0.6", features = ["gnome_44"] }
lazy_static = { version = "1.4" }
libc = { version = "0.2" }
libudev-sys = { version = "0.1" }
minidl = { version = "0.1" }
num_cpus = { version = "1" }
pathfinder_canvas = { git = "https://github.com/servo/pathfinder", rev = "21ec6fa933547636bc6c5ee8f0dd4a0ea3fcd062" }
pathfinder_color = { git = "https://github.com/servo/pathfinder", rev = "21ec6fa933547636bc6c5ee8f0dd4a0ea3fcd062" }
pathfinder_geometry = { git = "https://github.com/servo/pathfinder", rev = "21ec6fa933547636bc6c5ee8f0dd4a0ea3fcd062" }
pathfinder_gl = { git = "https://github.com/servo/pathfinder", rev = "21ec6fa933547636bc6c5ee8f0dd4a0ea3fcd062" }
pathfinder_gpu = { git = "https://github.com/servo/pathfinder", rev = "21ec6fa933547636bc6c5ee8f0dd4a0ea3fcd062" }
pathfinder_renderer = { git = "https://github.com/servo/pathfinder", rev = "21ec6fa933547636bc6c5ee8f0dd4a0ea3fcd062" }
pathfinder_resources = { git = "https://github.com/servo/pathfinder", rev = "21ec6fa933547636bc6c5ee8f0dd4a0ea3fcd062" }
raw-cpuid = { version = "11.0", default-features = false }
regex = { version = "1.8" }
rust-ini = { version = "0.19" }
rusqlite = { version = "0.29", features = ["bundled"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
sysinfo = { version = "0.29", default-features = false }
textdistance = { version = "1.0.2" }

[profile.release]
opt-level = 3
lto = true
